name: Deploy docs

on:
  push:
    branches:
      - main
    paths:
      - 'include/**'
      - 'docs/**'
      - 'Doxyfile'
      - '.github/workflows/doxygen.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check out Doxygen theme
      uses: actions/checkout@v4
      with:
        repository: jothepro/doxygen-awesome-css
        path: docs/doxygen-awesome-css
        # v2.3.1
        ref: df88fe4fdd97714fadfd3ef17de0b4401f804052

    - name: Install doxygen 1.9.6
      env:
        DOXYGEN_VERSION: 1.9.6
      run: |
        wget https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
        tar xzvf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
        cd doxygen-${DOXYGEN_VERSION}
        sudo make install

    - name: Run Doxygen
      run: |
        doxygen ./Doxyfile

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/html

  deploy:
    environment:
      name: github-pages
      url: matyalatte.github.io/c-env-utils
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
